name: Cypress Cross-Browser Tests

on:
  push:
    branches:
      - main

jobs:
  cross-browser:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, electron]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in ${{ matrix.browser }} and record to Cypress Cloud
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
